version: '3'
services:
  jupyter:
    image: jupyter/scipy-notebook:x86_64-ubuntu-22.04
    container_name: jupyter_notebook
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
    networks:
      - network1

volumes:
  notebooks:
    name: jupyter_notebook
    driver: local

networks:
  network1:
    name: docker_network
    external: true