version: '3'
services:
  notebooks:
    image: jupyter/scipy-notebook:x86_64-ubuntu-22.04
    container_name: notebooks
    ports:
      - "8888:8888"
    volumes:
      - notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
    networks:
      - network1

volumes:
  notebooks:
    name: notebooks
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data

networks:
  network1:
    name: docker_network
    external: true