version: '3'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.3
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://192.168.5.27:9200
    networks:
      - network1

networks:
  network1:
    name: docker_network
    external: true

