version: '3.8'

services:
  mongo1:
    container_name: mongo1
    image: mongo
    volumes:
      - ./data/mongo1:/data/db
      - ./rs-init.sh:/scripts/rs-init.sh
    networks:
      - network1
    ports:
      - 27017:27017
    links:
      - mongo2
      - mongo3
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
  mongo2:
    container_name: mongo2
    image: mongo
    volumes:
      - ./data/mongo2:/data/db
    networks:
      - network1
    ports:
      - 27018:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
  mongo3:
    container_name: mongo3
    image: mongo
    volumes:
      - ./data/mongo3:/data/db
    networks:
      - network1
    ports:
      - 27019:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
    networks:
      - network1

networks:
  network1:
    name: docker_network
    external: true

