global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: "codelab-monitor"

rule_files:
  - "prometheus.rules.yml"

scrape_configs:
  - job_name: "node"
    scrape_interval: 5s
    static_configs: 
      - targets: ["node-exporter:9100"]
        labels: 
          group: "production"
      # - targets: ["node-exporter2:9100", "node-exporter3:9100"]
      #   labels:
      #     group: "canary"
