version: '3.8'

services:
  keycloak:
    image: keycloak/keycloak:22.0
    container_name: keycloak
    ports:
      - "8090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: "start-dev --features=preview"
    restart: always
    volumes:
      - ./data:/opt/keycloak/data/
      - ./keycloak.conf:/opt/keycloak/conf/keycloak.conf
    networks:
      - network1

networks:
  network1:
    name: docker_network
    external: true
