FROM eclipse-temurin:17-jdk-alpine

ARG APPLICATION_USER=spring

RUN addgroup --system $APPLICATION_USER && adduser --system $APPLICATION_USER --ingroup $APPLICATION_USER

RUN mkdir /app && chown -R $APPLICATION_USER /app

USER $APPLICATION_USER

COPY --chown=$APPLICATION_USER:$APPLICATION_USER spring-app/build/libs/*.jar /app/app.jar

WORKDIR /app

EXPOSE 8090

ENTRYPOINT ["java", "-jar", "/app/app.jar"]

