FROM openjdk:17-jdk-slim

WORKDIR /app

RUN addgroup --system spring && adduser --system spring --ingroup spring

USER spring:spring

COPY spring-app/build/libs/*.jar /app/app.jar

EXPOSE 8090

CMD ["java", "-jar", "app.jar"]
