version: '3.8'
services:
  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    ports:
      - "3008:3000"
    restart: unless-stopped
    user: "1000"
    environment:
      GF_LOG_LEVEL: debug
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,grafana-piechart-panel"
    volumes:
      - ./data:/var/lib/grafana
      - ./datasources:/etc/grafana/provisioning/datasources
    networks:
      - network1

networks:
  network1:
    name: docker_network
    external: true