service:
  user: http://172.17.0.1:9001
  talent: http://172.17.0.1:9002
  client: http://172.17.0.1:9003
  media: http://172.17.0.1:9004
  finance: http://172.17.0.1:9005
  cms: http://172.17.0.1:6666

logging.level:
  org.springframework.cloud.gateway: TRACE
  org.springframework.security: TRACE
  org.springframework.web.reactive.function.client: TRACE
