spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: user
          uri: http://172.17.0.1:9001
          predicates:
            - Path=/user/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: talent
          uri: http://172.17.0.1:9002
          predicates:
            - Path=/talent/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: client
          uri: http://172.17.0.1:9003
          predicates:
            - Path=/client/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: media
          uri: http://172.17.0.1:9004
          predicates:
            - Path=/media/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: finance
          uri: http://172.17.0.1:9005
          predicates:
            - Path=/finance/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: cms
          uri: http://172.17.0.1:6666
          predicates:
            - Path=/cms/**
          filters:
            - RemoveRequestHeader=Cookie

  main:
    web-application-type: reactive

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/fandelo_one

server.port: ${port:9000}

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: TRACE
  org.springframework.web.reactive.function.client: TRACE