service:
  user: http://localhost:9001
  talent: http://localhost:9002
  client: http://localhost:9003
  media: http://localhost:9004
  finance: http://localhost:9005
  cms: http://localhost:6666

logging.level:
  org.springframework.cloud.gateway: TRACE
  org.springframework.security: TRACE
  org.springframework.web.reactive.function.client: TRACE
