server:
  port: 9001
  servlet:
    context-path: /user


spring:
  config:
    activate:
      on-profile: dev

  security:
    user:
      name: admin
      password: admin
    oauth2:
      client:
        registration:
          external:
            provider: external
            client-id: fandelo_one
            client-secret: D1WwN1LZA0Bc7WunTIOsM86bd9ewk1v1
            scope: openid,offline_access,profile
            authorization-grant-type: authorization_code
        provider:
          external:
            issuer-uri: http://172.17.0.1:8080/realms/fandelo_one
      resourceserver:
        jwt:
          issuer-uri: http://172.17.0.1:8080/realms/fandelo_one

  data:
    redis:
      host: redis
      password:
      port: 6379

  threads:
    virtual:
      enabled: true

google:
  recaptcha:
    key:
      site: 6LdY4FkdAAAAAOhcwRe-JH1ONWCRkknWmddDtxZh
      secret: 6LdY4FkdAAAAAAK0bWIuILF00rzA-2-P-myxaHl-
      threshold: 0.5

keycloak:
  realm: fandelo_one
  server-url: http://172.17.0.1:8080
  admin-client-id: admin-cli
  grant-type: password
  username: admin
  password: admin
