version: '3.8'

services:
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile
    image: rabbitmq:delay-queue
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./data:/var/lib/rabbitmq
    env:
      - RABBITMQ_DEFAULT_USER: guest
      - RABBITMQ_DEFAULT_PASS: guest
      - RABBITMQ_DEFAULT_VHOST: dev_dorsal
    networks:
      - network1

networks:
  network1:
    name: docker_network
    external: true


    container_name: rabbitmq