version: '3.8'

services:
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile
    image: rabbitmq:delay-queue
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./data:/var/lib/rabbitmq
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5672"]
      timeout: 10s
      retries: 3
      interval: 15s
      start_period: 30s
    networks:
      - network1

networks:
  network1:
    name: docker_network
    external: true