name: 'mongodb'

services:
  mongo1:
    container_name: mongo1
    image: bitnami/mongodb:7.0.14
    hostname: mongo1
    volumes:
      - mongo1:/bitnami/mongodb
      - ./config/mongo1-mongod.conf:/opt/bitnami/mongodb/conf/mongodb.conf
      - ./pki/mongod-keyfile:/opt/bitnami/mongodb/pki/mongod-keyfile
    networks:
      - network1
    ports:
      - 27017:27017
    restart: on-failure
  mongo2:
    container_name: mongo2
    image: bitnami/mongodb:7.0.14
    hostname: mongo2
    volumes:
      - mongo2:/bitnami/mongodb
      - ./config/mongo2-mongod.conf:/opt/bitnami/mongodb/conf/mongodb.conf
      - ./pki/mongod-keyfile:/opt/bitnami/mongodb/pki/mongod-keyfile
    networks:
      - network1
    ports:
      - 27018:27017
    restart: on-failure
  mongo3:
    container_name: mongo3
    image: bitnami/mongodb:7.0.14
    hostname: mongo3
    volumes:
      - mongo3:/bitnami/mongodb
      - ./config/mongo3-mongod.conf:/opt/bitnami/mongodb/conf/mongodb.conf
      - ./pki/mongod-keyfile:/opt/bitnami/mongodb/pki/mongod-keyfile
    networks:
      - network1
    ports:
      - 27019:27017
    restart: on-failure

networks:
  network1:
    name: docker_network
    external: true

volumes:
  mongo1:
    driver: local
  mongo2:
    driver: local
  mongo3:
    driver: local
