version: '3.9'
services:
  redisinsight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis-insight
    restart: always
    ports:
      - "8001:8001"
    networks:
      - network1

networks:
  network1:
    name: docker_network
    external: true