version: '3.8'

services:
  gateway:
    image: gateway:1.0
    container_name: gateway
    ports:
      - "9000:9000"
    restart: on-failure
    environment:
      BASE_DIR: .
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - hostnet

  user:
    image: user:1.0
    container_name: user
    ports:
      - "9001:9001"
    restart: on-failure
    environment:
      BASE_DIR: .
      SPRING_PROFILES_ACTIVE: dev
      AWS_REGION: ap-southeast-2
    networks:
      - hostnet

networks:
  hostnet:
    external: true
    name: docker_network
