service:
  user: ${USER_SERVICE_URL}
  talent: ${TALENT_SERVICE_URL}
  client: ${CLIENT_SERVICE_URL}
  media: ${MEDIA_SERVICE_URL}
  finance: ${FINANCE_SERVICE_URL}
  cms: ${CMS_SERVICE_URL}

logging.level:
  org.springframework.cloud.gateway: TRACE
  org.springframework.security: TRACE
  org.springframework.web.reactive.function.client: TRACE
