version: '3.8'
services:
  apache:
    image: httpd:prism-frontend
    container_name: apache
    ports:
      - 8080:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      start_period: 20s
      retries: 3
      timeout: 10s
    mem_limit: 1024m
    mem_reservation: 128M
    cpus: 0.5
    restart: unless-stopped
    networks:
      - "network1"

networks:
  network1:
    name: docker_network
    external: true