name: mysql

services:
  database:
    image: mysql:9.0.1
    container_name: mysql
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    # environment:
    #   MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    #   MYSQL_DATABASE: ${MYSQL_DATABASE}
    #   MYSQL_USER: ${MYSQL_USER}
    #   MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf
      # - ./prerequisite.sh:/prerequisite.sh
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-p${password}"]
      timeout: 10s
      retries: 3
      interval: 15s
      start_period: 30s
    mem_limit: 1024m
    mem_reservation: 128M
    cpus: 0.5
    networks:
      - docker_network

networks:
  docker_network:
    name: docker_network
    driver: bridge

