version: '3.1'

services:
  ghost:
    image: ghost:alpine
    container_name: ghost
    restart: on-failure
    ports:
      - "2368:2368"
    volumes:
      - ./data:/var/lib/ghost/content
    env_file:
      - .env
    networks:
      - network1
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/localhost/2368/ghost/api/v4/admin/site/' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s

networks:
  network1:
    name: docker_network
    external: true
