name: minio

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-02-28T09-55-16Z
    container_name: minio
    restart: on-failure
    ports:
      - "9000:9000"
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "alias", "set", "local", "http://localhost:9000", "admin", "password"]
      interval: 30s
      timeout: 20s
      retries: 3
    mem_reservation: 128M
    networks:
      - docker_network

networks:
  docker_network:
    name: docker_network
    driver: bridge