version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 15432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    #  - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - network1

  #pgadmin:
  #  image: dpage/pgadmin4
  #  container_name: pgadmin
  #  ports:
  #    - 15433:80
  #  env_file:
  #    - .env
  #  depends_on:
  #    - postgres
  #  networks:
  #    - network1
  #  volumes:
  #    - ./pgadmin/:/var/lib/pgadmin/
    
networks:
  network1:
    name: docker_network
    external: true
