version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    #command: ["--replSet", "rs0", "--bind_ip_all"]
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
    ports:
      - "27017:27017"
    volumes:
      - "./rs-init.sh:/scripts/rs-init.sh"
      - "./data:/data/db"
      - "./mongod.conf:/etc/mongod.conf"
      - "./keyfile:/etc/mongod/keyfile"  # Mount the key file
    networks:
      - network1

networks:
  network1:
    name: docker_network
    external: true

