version: '3.9'
services:
  redis:
    image: redis:bookworm
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    restart: always
    networks:
      - network1

  redisinsight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis-insight
    restart: always
    ports:
      - "8001:8001"
    networks:
      - network1

networks:
  network1:
    name: docker_network
    external: true
