version: '3.9'
services:
  redis:
    image: redis:bookworm
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    restart: on-failure
    networks:
      - network1
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      timeout: 10s
      retries: 3
      interval: 15s
      start_period: 30s

  redisinsight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis-insight
    restart: always
    ports:
      - "8001:8001"
    networks:
      - network1

networks:
  network1:
    name: docker_network
    external: true
